child_lock: true
comfort_temp: 19
eco_temp: 18
name: Spring
schedules:
  friday:
  - end: '12:00'
    start: 07:00
  - end: '21:00'
    start: '12:10'
  monday:
  - end: '12:00'
    start: 07:00
  - end: '21:00'
    start: '12:10'
  saturday:
  - end: '12:00'
    start: 07:00
  - end: '21:00'
    start: '12:10'
  sunday:
  - end: '12:00'
    start: 07:00
  - end: '21:00'
    start: '12:10'
  thursday:
  - end: '12:00'
    start: 07:00
  - end: '21:00'
    start: '12:10'
  tuesday:
  - end: '12:00'
    start: 07:00
  - end: '21:00'
    start: '12:10'
  wednesday:
  - end: '12:00'
    start: 07:00
  - end: '21:00'
    start: '12:10'
