name: Winter
comfort_temp: 22.5
eco_temp: 19.0
schedules:
  monday:
    - {start: "07:00", end: "12:00"}
    - {start: "12:10", end: "19:00"}
  tuesday:
    - {start: "07:00", end: "12:00"}
    - {start: "12:10", end: "19:00"}
  wednesday:
    - {start: "07:00", end: "12:00"}
    - {start: "12:10", end: "19:00"}
  thursday:
    - {start: "07:00", end: "12:00"}
    - {start: "12:10", end: "19:00"}
  friday:
    - {start: "07:00", end: "12:00"}
    - {start: "12:10", end: "19:00"}
  saturday:
    - {start: "07:00", end: "12:00"}
    - {start: "12:10", end: "19:00"}
  sunday:
    - {start: "07:00", end: "12:00"}
    - {start: "12:10", end: "19:00"}
